#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: conecta o repo calculadora-investimento na conta Vercel do CLIENTE
# e liga um subdomínio dele à calculadora.
#
# Pré-requisito: você já está logado na Vercel do cliente (ou tem acesso à
# conta/team dele), e o GitHub dele já foi adicionado como colaborador no
# repositório github.com/JuanGabrielGomes/calculadora-investimento.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
# Força o arquivo de estado do wizard pra dentro de scripts/, mesmo a
# biblioteca acima já tendo aplicado o padrão ".env" (por isso não usamos
# "${ENV_FILE:-...}" aqui — nesse ponto ENV_FILE já não está mais vazio).
ENV_FILE="scripts/conectar-vercel-cliente.env"

banner "Conectar calculadora-investimento na Vercel do cliente"

# ── Stage 1: confirmar que está na conta certa ─────────────────────────────
stage "Confirmar a conta Vercel do cliente"
say "Antes de importar, confirme que está mexendo na conta/team da VERCEL DO"
say "CLIENTE — não na sua conta pessoal."
open_url "https://vercel.com/dashboard"
step "No canto superior esquerdo, veja o nome da conta/team ativa."
step "Se não for a do cliente, clique nela e troque de conta/team no menu."
ask CLIENT_VERCEL_SCOPE "Nome da conta/team da Vercel do cliente (o que apareceu no canto superior esquerdo):"
write_env CLIENT_VERCEL_SCOPE "$CLIENT_VERCEL_SCOPE"

# ── Stage 2: garantir que o GitHub App da Vercel enxerga o repo ────────────
stage "Liberar o repositório para o GitHub App da Vercel"
say "A conta do cliente ser colaboradora no repo não é suficiente sozinha:"
say "o GitHub App 'Vercel' também precisa ter permissão de ver esse repo"
say "para a conta/GitHub que está conectado à Vercel do cliente."
note "Isso só precisa ser feito uma vez por cliente."
step "Ao importar (próximo passo), se 'calculadora-investimento' NÃO aparecer"
step "na lista de repositórios, clique em 'Adjust GitHub App Permissions'."
step "Isso abre o GitHub: em 'Repository access', escolha 'Only select"
step "repositories' e adicione JuanGabrielGomes/calculadora-investimento"
step "(só aparece como opção porque o cliente já é colaborador nele)."
pause "Entendido — seguimos pro import"

# ── Stage 3: importar e fazer o deploy do projeto ──────────────────────────
stage "Importar o projeto na Vercel"
open_url "https://vercel.com/new"
step "Confirme de novo, no topo da página, que o scope selecionado é o do"
step "cliente (não o seu)."
step "Em 'Import Git Repository', procure calculadora-investimento e clique Import."
step "Framework Preset: deixe como 'Other' (é HTML/CSS/JS estático)."
warn "NÃO mude o 'Root Directory' — deixe na raiz do repo. O projeto já tem"
warn "um vercel.json que redireciona tudo pra clientes/maav-hub sozinho;"
warn "mudar o Root Directory quebra esse redirecionamento."
step "Não precisa adicionar nenhuma Environment Variable."
step "Clique em Deploy e espere terminar (uns 30 segundos)."
pause "Deploy concluído?"

# ── Stage 4: verificar o deploy ─────────────────────────────────────────────
stage "Verificar o deploy"
say "A Vercel mostra a URL tipo *.vercel.app assim que o deploy termina."
step "Abra essa URL e confirme que a calculadora carrega normalmente,"
step "com os valores e o botão funcionando."
ask VERCEL_APP_URL "Cole aqui o domínio *.vercel.app que a Vercel gerou (sem https://):"
VERCEL_APP_URL="${VERCEL_APP_URL#https://}"
VERCEL_APP_URL="${VERCEL_APP_URL#http://}"
write_env VERCEL_APP_URL "$VERCEL_APP_URL"
open_url "https://$VERCEL_APP_URL"
confirm "A calculadora carregou certinho nessa URL?" || warn "resolva isso antes de seguir pro domínio — o restante depende do deploy estar OK"

# ── Stage 5: adicionar o subdomínio no projeto ─────────────────────────────
stage "Adicionar o subdomínio do cliente"
ask CLIENT_SUBDOMAIN "Qual vai ser o subdomínio? (ex: calculadora.dominiodocliente.com.br)"
write_env CLIENT_SUBDOMAIN "$CLIENT_SUBDOMAIN"
step "No projeto na Vercel, vá em Settings → Domains."
step "Digite o subdomínio ($CLIENT_SUBDOMAIN) e clique Add."
step "A Vercel vai mostrar um registro de DNS pra você criar (geralmente um"
step "CNAME apontando pra cname.vercel-dns.com, às vezes um registro A)."
say "Anote esse registro exatamente como a Vercel mostrar — o valor exato"
say "pode variar conforme o tipo de domínio (subdomínio vs. domínio raiz)."
ask DNS_RECORD_TYPE "Tipo do registro que a Vercel pediu (CNAME ou A):"
ask DNS_RECORD_VALUE "Valor/destino que a Vercel mostrou para esse registro:"
write_env DNS_RECORD_TYPE "$DNS_RECORD_TYPE"
write_env DNS_RECORD_VALUE "$DNS_RECORD_VALUE"

# ── Stage 6: criar o registro de DNS ────────────────────────────────────────
stage "Criar o registro de DNS"
ask DNS_PROVIDER "Onde fica o DNS desse domínio? (Registro.br, Cloudflare, GoDaddy, HostGator...)"
write_env DNS_PROVIDER "$DNS_PROVIDER"
say "Abra o painel de DNS em: $DNS_PROVIDER"
step "Crie um registro $DNS_RECORD_TYPE com host/nome = a parte do subdomínio"
step "antes do domínio (ex: em calculadora.dominiodocliente.com.br, o host é"
step "'calculadora'), apontando para: $DNS_RECORD_VALUE"
step "Deixe o TTL no padrão do provedor."
note "Propagação de DNS pode levar de alguns minutos até algumas horas."
pause "Registro de DNS criado?"

# ── Stage 7: confirmar o domínio e o HTTPS na Vercel ───────────────────────
stage "Confirmar o domínio na Vercel"
step "Volte em Settings → Domains no projeto da Vercel."
step "Clique em 'Refresh' ao lado do domínio até aparecer 'Valid Configuration'."
note "Se ainda não validou, espere a propagação do DNS e clique Refresh de novo."
step "A Vercel emite o certificado HTTPS sozinha assim que o DNS valida."
ask FINAL_URL "Confirme a URL final funcionando (ex: https://calculadora.dominiodocliente.com.br):"
write_env FINAL_URL "$FINAL_URL"
open_url "$FINAL_URL"
confirm "Carregou certinho com HTTPS (cadeado) na URL final?"
# ──────────────────────────────────────────────────────────────────────────

finish
